#include "HoloPlayProInputDefinitions.h"

const FKey FHoloPlayProInputKeys::GlobalGesture_DoubleTap(GlobalGestureDoubleTapName);
const FKey FHoloPlayProInputKeys::HoloPlayViewportGesture_DoubleTap(HoloPlayViewportGestureDoubleTapName);